# This file tells https://pre-commit.com/
# which hooks are provided by this repo
# for use by other git repos.

- id: make-test
  name: Run quick unit tests with 'make test' before commit
  description: Run quick unit tests with 'make test' before commit
  entry: pre_commit_hooks/make_test
  language: script

- id: make
  name: Run 'make ${target}' before commit
  description: Run 'make ${target}' before commit
  entry: make
  language: system
  always_run: true
  pass_filenames: false

- id: identity
  name: Echo back all arguments.
  description: Echo back all arguments. Useful for debugging.
  entry: pre_commit_hooks/identity
  language: script
  always_run: true

- id: echo
  name: Echo back all arguments.
  description: Echo back all arguments. Useful for debugging.
  entry: echo
  language: system
  always_run: true
